# Generated by Django 5.2.4 on 2025-07-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beneficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Descuento", "Descuento"), ("Servicio", "Servicio")],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Convenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Hospedaje", "Hospedaje"),
                            ("Salud", "Salud"),
                            ("Gastronomía", "Gastronomía"),
                        ],
                        max_length=100,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                        default="Activo",
                        max_length=50,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("sitio_web", models.URLField(blank=True)),
            ],
        ),
    ]
