# Generated by Django 4.2.23 on 2025-07-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='convenios/', verbose_name='Imagen del Convenio'),
        ),
    ]
