# Generated by Django 5.2.4 on 2025-07-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolicitudAfiliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=200)),
                ("ruc", models.CharField(max_length=13)),
                ("direccion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
