# Generated by Django 5.2.4 on 2025-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afiliaciones", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="ruc",
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="beneficiario_nombre",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="beneficiario_pct",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Porcentaje del Beneficiario"
            ),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="copia_cedula",
            field=models.FileField(
                blank=True, null=True, upload_to="afiliaciones/cedulas/"
            ),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="copia_ruc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="afiliaciones/ruc/",
                verbose_name="Copia de RUC",
            ),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="direccion_comercial",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="documento_adicional",
            field=models.FileField(
                blank=True, null=True, upload_to="afiliaciones/adicionales/"
            ),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="estado_provincia",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="firma_electronica",
            field=models.FileField(
                blank=True, null=True, upload_to="afiliaciones/firmas/"
            ),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="nombre_comercial",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="red_social_preferida",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("LINKEDIN", "LinkedIn"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="tipo_actividad",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="tipo_negocio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMERCIAL", "Comercial"),
                    ("INDUSTRIAL", "Industrial"),
                    ("SERVICIOS", "Servicios"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="titular_cedula",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="titular_nombre",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="titular_telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
