# Generated by Django 5.2.4 on 2025-07-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afiliaciones", "0003_remove_solicitudafiliacion_direccion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="ruc",
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
