# Generated by Django 5.2.4 on 2025-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afiliaciones", "0004_solicitudafiliacion_ruc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="beneficiario_nombre",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="beneficiario_pct",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="ciudad",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="copia_cedula",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="copia_ruc",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="direccion_comercial",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="documento_adicional",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="estado_provincia",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="firma_electronica",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="nombre_comercial",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="red_social_preferida",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="tipo_actividad",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="tipo_negocio",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="titular_cedula",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="titular_nombre",
        ),
        migrations.RemoveField(
            model_name="solicitudafiliacion",
            name="titular_telefono",
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="direccion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitudafiliacion",
            name="ruc",
            field=models.CharField(max_length=13),
        ),
    ]
