# Generated by Django 5.2.4 on 2025-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "afiliaciones",
            "0005_remove_solicitudafiliacion_beneficiario_nombre_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="solicitudafiliacion",
            old_name="direccion",
            new_name="direccion_comercial",
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="beneficiario_nombre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="beneficiario_pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="ciudad",
            field=models.CharField(default="Loja", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="copia_cedula",
            field=models.FileField(blank=True, null=True, upload_to="afiliaciones/"),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="copia_ruc",
            field=models.FileField(blank=True, null=True, upload_to="afiliaciones/"),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="documento_adicional",
            field=models.FileField(blank=True, null=True, upload_to="afiliaciones/"),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="estado_provincia",
            field=models.CharField(default="Loja", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="firma_electronica",
            field=models.FileField(blank=True, null=True, upload_to="afiliaciones/"),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="nombre_comercial",
            field=models.CharField(default="nombre1", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="red_social_preferida",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="tipo_actividad",
            field=models.CharField(default="actividad1", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="tipo_negocio",
            field=models.CharField(default="negocio", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="titular_cedula",
            field=models.CharField(default="titular", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="titular_nombre",
            field=models.CharField(default="Nombre", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="solicitudafiliacion",
            name="titular_telefono",
            field=models.CharField(default="telefono", max_length=20),
            preserve_default=False,
        ),
    ]
