# Generated by Django 5.2.4 on 2025-07-26 16:07

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='persona_set', related_query_name='persona', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='persona_set', related_query_name='persona', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('asunto', models.CharField(choices=[('afiliacion', 'Información sobre Afiliación'), ('certificaciones', 'Certificaciones y Documentos'), ('mediacion', 'Centro de Mediación'), ('capacitacion', 'Capacitación Empresarial'), ('eventos', 'Eventos y Networking'), ('servicios', 'Servicios Empresariales'), ('comercio_exterior', 'Comercio Exterior'), ('otro', 'Otro')], max_length=30)),
                ('mensaje', models.TextField()),
                ('acepto_politicas', models.BooleanField(default=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Hospedaje', 'Hospedaje'), ('Salud', 'Salud'), ('Gastronomía', 'Gastronomía'), ('Deportes', 'Deportes'), ('Educación', 'Educación'), ('Otros', 'Otros')], max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Por Vencer', 'Por Vencer'), ('Vencido', 'Vencido')], default='Activo', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('contacto_nombre', models.CharField(blank=True, max_length=255)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_camara_comercio.persona')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('app_camara_comercio.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_camara_comercio.persona')),
                ('tipo_plan', models.CharField(choices=[('persona_natural', 'Plan Persona Natural'), ('empresa', 'Plan Empresa'), ('entidad_financiera', 'Plan Entidad Financiera')], max_length=20, verbose_name='Tipo de Plan')),
                ('fecha_afiliacion', models.DateField(auto_now_add=True, verbose_name='Fecha de afiliación')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('RUC', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('nombre_representante_legal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Representante Legal')),
                ('cedula_representante', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Representante Legal')),
                ('fecha_visita', models.DateField(blank=True, null=True, verbose_name='Fecha de visita')),
                ('red_social_preferida', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('tiktok', 'Tik Tok')], max_length=20, null=True, verbose_name='Red social que más usa')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('tipo_negocio', models.CharField(blank=True, choices=[('comercio', 'Comercio'), ('servicios', 'Servicios'), ('importacion_exportacion', 'Importación/Exportación'), ('industria', 'Industria'), ('otro', 'Otro')], max_length=30, null=True, verbose_name='Tipo de Negocio')),
                ('acepta_terminos', models.BooleanField(default=False, verbose_name='Acepto los términos y condiciones')),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
            },
            bases=('app_camara_comercio.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Descuento', 'Descuento'), ('Servicio', 'Servicio'), ('Producto', 'Producto'), ('Especial', 'Especial'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='app_camara_comercio.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='app_camara_comercio.beneficio')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_camara_comercio.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('publicada', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='app_camara_comercio.administrador')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AddField(
            model_name='convenio',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convenios_creados', to='app_camara_comercio.administrador'),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('servicio_especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_camara_comercio.servicioespecifico', verbose_name='Servicio Específico')),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app_camara_comercio.afiliado')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosAfiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_nombres', models.CharField(max_length=200, verbose_name='Nombres Completos Titular')),
                ('titular_telefono', models.CharField(max_length=20, verbose_name='Teléfono Titular')),
                ('titular_cedula', models.CharField(max_length=20, verbose_name='Cédula Titular')),
                ('beneficiario_nombres', models.CharField(max_length=200, verbose_name='Nombres Completos Beneficiario')),
                ('beneficiario_porcentaje', models.PositiveIntegerField(verbose_name='Porcentaje Beneficiario')),
                ('copia_ruc', models.FileField(upload_to='documentos/ruc/', verbose_name='Copia de RUC')),
                ('copia_cedula', models.FileField(blank=True, null=True, upload_to='documentos/cedula/', verbose_name='Copia de Cédula')),
                ('copia_nombramiento', models.FileField(blank=True, null=True, upload_to='documentos/nombramiento/', verbose_name='Copia de Nombramiento')),
                ('firma_electronica', models.FileField(upload_to='documentos/firmas/', verbose_name='Firma Electrónica')),
                ('consentimiento_datos', models.BooleanField(default=False, verbose_name='Consentimiento Protección de Datos')),
                ('afiliado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_camara_comercio.afiliado')),
            ],
            options={
                'verbose_name': 'Documentos de Afiliado',
                'verbose_name_plural': 'Documentos de Afiliados',
            },
        ),
    ]
