# Generated by Django 5.2.4 on 2025-07-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_camara_comercio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
