# Generated by Django 5.2.4 on 2025-07-28 23:13

import app_camara_comercio.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_camara_comercio', '0002_delete_noticia'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrador',
            managers=[
                ('objects', app_camara_comercio.managers.PersonaManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='afiliado',
            managers=[
                ('objects', app_camara_comercio.managers.PersonaManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='persona',
            managers=[
                ('objects', app_camara_comercio.managers.PersonaManager()),
            ],
        ),
    ]
