# Generated by Django 5.2.4 on 2025-07-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=15)),
                ("asunto", models.CharField(max_length=100)),
                ("mensaje", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
