# Generated by Django 5.2.4 on 2025-07-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('CAPACITACION', 'Capacitación'), ('CONSULTORIA', 'Consultoría'), ('TRAMITES', 'Trámites'), ('EVENTOS', 'Eventos')], max_length=50)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('activo', models.BooleanField(default=True)),
                ('solo_socios', models.BooleanField(default=False, help_text='Si está marcado, solo los socios pueden acceder')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
