# Generated by Django 5.2.4 on 2025-07-29 03:12

import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", usuarios.models.UsuarioManager()),
            ],
        ),
    ]
