# Generated by Django 5.2.4 on 2025-07-30 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "equipamiento",
                    models.TextField(
                        blank=True, help_text="Equipos y recursos disponibles"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Lugar",
                "verbose_name_plural": "Lugares",
            },
        ),
        migrations.CreateModel(
            name="TipoLugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("capacidad_maxima", models.PositiveIntegerField()),
                (
                    "precio_por_hora",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Lugar",
                "verbose_name_plural": "Tipos de Lugares",
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                (
                    "proposito",
                    models.CharField(
                        help_text="Propósito de la reserva", max_length=200
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, help_text="Detalles adicionales"),
                ),
                ("numero_personas", models.PositiveIntegerField(default=1)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("cancelada", "Cancelada"),
                            ("completada", "Completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                (
                    "notas_admin",
                    models.TextField(blank=True, help_text="Notas del administrador"),
                ),
                (
                    "aprobada_por",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lugar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="reservas.lugar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.AddField(
            model_name="lugar",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lugares",
                to="reservas.tipolugar",
            ),
        ),
    ]
