# Generated by Django 5.2.4 on 2025-07-31 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lugar",
            options={},
        ),
        migrations.AlterModelOptions(
            name="reserva",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tipolugar",
            options={},
        ),
        migrations.RenameField(
            model_name="reserva",
            old_name="fecha_solicitud",
            new_name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="lugar",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="lugar",
            name="equipamiento",
        ),
        migrations.RemoveField(
            model_name="lugar",
            name="ubicacion",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="aprobada_por",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="fecha_aprobacion",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="notas_admin",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="numero_personas",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="proposito",
        ),
        migrations.RemoveField(
            model_name="tipolugar",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="lugar",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lugares/",
                verbose_name="Imagen del Lugar",
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="notas_adicionales",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lugar",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="lugar",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lugares",
                to="reservas.tipolugar",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="lugar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservas.lugar"
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tipolugar",
            name="capacidad_maxima",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tipolugar",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tipolugar",
            name="precio_por_hora",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
