# Generated by Django 5.2.4 on 2025-07-31 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0003_alter_reserva_options_reserva_fecha_actualizacion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reserva",
            options={},
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="proposito",
        ),
        migrations.AddField(
            model_name="lugar",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="Marcar para que este lugar sea visible al público.",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="lugar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservas.lugar"
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
