# Generated by Django 4.2.23 on 2025-07-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_add_proposito_field'),
        ('reservas', '0006_add_proposito_field'),
    ]

    operations = [
    ]
