# Generated by Django 5.2.3 on 2025-07-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_merge_20250731_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='proposito',
            field=models.CharField(blank=True, help_text='Propósito de la reserva', max_length=255, null=True, verbose_name='Propósito'),
        ),
    ]
